# Generated by Django 4.1.2 on 2022-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(help_text='Enter your first name here', max_length=20, verbose_name='First name')),
                ('lName', models.CharField(help_text='Enter your last name here', max_length=20, verbose_name='Last name')),
                ('email', models.EmailField(help_text='Enter your email here', max_length=254)),
                ('number', models.CharField(help_text='Enter your phone number here', max_length=11)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Nonbinary', 'Nonbinary'), ('Other', 'Other')], default='Female', max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
    ]
