# Generated by Django 4.1.2 on 2022-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='variables',
        ),
        migrations.AddField(
            model_name='variable',
            name='users',
            field=models.ManyToManyField(to='homepage.profile'),
        ),
    ]
