# Generated by Django 4.1.2 on 2022-11-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_userdata_remove_profile_variables_variable_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='variables',
            field=models.ManyToManyField(to='homepage.variable'),
        ),
    ]
