# Generated by Django 4.1.2 on 2022-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_variable_users_profile_variables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AddField(
            model_name='profile',
            name='data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
