# Generated by Django 4.1.2 on 2022-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_delete_userdata_profile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorical_variable',
            name='choices',
            field=models.CharField(help_text='enter your categories here (comma separated), enter Y,N for binary variable', max_length=500),
        ),
    ]
