# Generated by Django 4.1.2 on 2022-11-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_categorical_variable_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorical_variable',
            name='is_binary',
        ),
        migrations.AlterField(
            model_name='categorical_variable',
            name='choices',
            field=models.CharField(help_text='enter your categories here (comma separated)', max_length=500),
        ),
    ]
