# Generated by Django 4.1.2 on 2022-11-15 16:39

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_categorical_variable_is_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='is_continuous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorical_variable',
            name='choices',
            field=models.CharField(help_text='enter your categories here (comma separated)', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
