# Generated by Django 4.1.2 on 2022-11-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_variable_is_continuous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorical_variable',
            name='choices',
            field=models.CharField(help_text='enter your categories here (comma separated)', max_length=500),
        ),
    ]
