# Generated by Django 4.1.2 on 2022-11-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_rename_categorical_variable_categoricalvariable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='is_continuous',
            field=models.BooleanField(default=False),
        ),
    ]
