# Generated by Django 4.1.2 on 2022-11-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_variable_is_continuous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
