# Generated by Django 4.1.2 on 2022-11-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_variable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoricalvariable',
            name='is_binary',
            field=models.BooleanField(default=True),
        ),
    ]
