# Generated by Django 4.1.2 on 2023-04-08 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edit_variables', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Required. Enter your email.', max_length=254, unique=True)),
                ('number', models.CharField(help_text='Enter your phone number.', max_length=11)),
                ('gender', models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Non binary', 'Non binary'), ('Other', 'Other')], default='Woman', max_length=20)),
                ('dob', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('variables', models.ManyToManyField(related_name='users', to='edit_variables.variable')),
            ],
        ),
    ]
