# Generated by Django 4.1.2 on 2022-11-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Non binary', 'Non binary'), ('Other', 'Other')], default='Female', max_length=20),
        ),
    ]
