# Generated by Django 4.1.2 on 2022-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(help_text='Required. Enter your email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(help_text='Enter your phone number.', max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
