# Generated by Django 4.1.2 on 2022-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_alter_profile_email_alter_profile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(help_text='Required. Enter your email.', max_length=254, unique=True),
        ),
    ]
