# Generated by Django 4.1.2 on 2022-11-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Non binary', 'Non binary'), ('Other', 'Other')], default='Woman', max_length=20),
        ),
    ]
