# Generated by Django 4.1.2 on 2023-04-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prompt', models.CharField(max_length=250)),
                ('is_continuous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoricalVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edit_variables.variable')),
                ('is_binary', models.BooleanField(default=True)),
                ('choices', models.CharField(max_length=500)),
            ],
            bases=('edit_variables.variable',),
        ),
    ]
