# Generated by Django 4.1.2 on 2023-05-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit_variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edit_variables.variable')),
                ('scale_start', models.IntegerField(default=0, help_text='Start of scale, e.g. 0.')),
                ('scale_end', models.IntegerField(default=10, help_text='End of scale, e.g. 10.')),
            ],
            bases=('edit_variables.variable',),
        ),
    ]
