# Generated by Django 4.1.2 on 2023-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_variables', '0002_continuousvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuousvariable',
            name='scale_end',
        ),
        migrations.RemoveField(
            model_name='continuousvariable',
            name='scale_start',
        ),
        migrations.AddField(
            model_name='continuousvariable',
            name='lower_bound',
            field=models.IntegerField(default=10, help_text='End of scale'),
        ),
        migrations.AddField(
            model_name='continuousvariable',
            name='upper_bound',
            field=models.IntegerField(default=0, help_text='Start of scale'),
        ),
    ]
